// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package dbmanager

import (
	"context"
	"database/sql"
)

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (
    name,
    path,
    description,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, name, path, description, created_at, updated_at
`

type CreateDatabaseParams struct {
	Name        string
	Path        string
	Description sql.NullString
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRowContext(ctx, createDatabase,
		arg.Name,
		arg.Path,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDatabase = `-- name: DeleteDatabase :exec
DELETE FROM databases
WHERE id = ?
`

func (q *Queries) DeleteDatabase(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDatabase, id)
	return err
}

const getDatabase = `-- name: GetDatabase :one
SELECT
    id,
    name,
    path,
    description,
    created_at,
    updated_at
FROM databases
WHERE id = ?
`

func (q *Queries) GetDatabase(ctx context.Context, id int64) (Database, error) {
	row := q.db.QueryRowContext(ctx, getDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDatabases = `-- name: ListDatabases :many
SELECT
    id,
    name,
    path,
    description,
    created_at,
    updated_at
FROM databases
`

func (q *Queries) ListDatabases(ctx context.Context) ([]Database, error) {
	rows, err := q.db.QueryContext(ctx, listDatabases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Database
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDatabase = `-- name: UpdateDatabase :exec
UPDATE databases
SET
    name = ?,
    path = ?,
    description = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateDatabaseParams struct {
	Name        string
	Path        string
	Description sql.NullString
	UpdatedAt   string
	ID          int64
}

func (q *Queries) UpdateDatabase(ctx context.Context, arg UpdateDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, updateDatabase,
		arg.Name,
		arg.Path,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
