// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbmanaged

import (
	"database/sql"
)

type SqliteMaster struct {
	Type     sql.NullString
	Name     sql.NullString
	TblName  sql.NullString
	Rootpage sql.NullInt64
	Sql      sql.NullString
}
