// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package dbmanaged

import (
	"context"
	"database/sql"
)

const listTables = `-- name: ListTables :many
SELECT 
    name,
    type,
    tbl_name,
    sql
FROM sqlite_master
WHERE
    name NOT LIKE 'sqlite_%'
AND type IN ('table', 'view')
`

type ListTablesRow struct {
	Name    sql.NullString
	Type    sql.NullString
	TblName sql.NullString
	Sql     sql.NullString
}

func (q *Queries) ListTables(ctx context.Context) ([]ListTablesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTablesRow
	for rows.Next() {
		var i ListTablesRow
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.TblName,
			&i.Sql,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
